services:
  db:
    container_name: poindexter-db
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: poindexter-network
    volumes:
      - postgres:/data/postgres
    ports:
      - 6734:5432
    networks:
      - poindexter-net
    restart: unless-stopped
# I switched over to smtp.gmail
#  mail-dev:
#    container_name: mail-dev
#    image: maildev/maildev
#    ports:
#      - 1080:1080
#      - 1025:1025
  pn-api:
    container_name: pn-api
    image: pn/pn-api:1.0.3
    ports:
      - 8089:8089
    networks:
      - poindexter-net
    depends_on:
      - db
  pn-ui:
    container_name: pn-ui
    image: pn/pn-ui:1.0.1
    ports:
      - 8080:80
    networks:
      - poindexter-net
    depends_on:
      - pn-api
networks:
  poindexter-net:
    driver: bridge

volumes:
  postgres:
    driver: local