name: Poindexter Server API Pipeline

on:
  push:
    branches:
      - ci/pipeline
    paths:
      - poindexter-network/**
      - docker/server/**
      - "docker-compose.yml"
      - .github/workflows/*-server.yml

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile project
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set execute permissions for mvnw
        run: chmod +x poindexter-network/mvnw

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "corretto"

      - name: Set environment variables
        run: |
          echo "EMAIL_HOST_NAME=${{ secrets.EMAIL_HOST_NAME }}" >> $GITHUB_ENV
          echo "EMAIL_USER_NAME=${{ secrets.EMAIL_USER_NAME }}" >> $GITHUB_ENV
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV

      - name: Compile project
        run: |
          cd poindexter-network
          ./mvnw clean compile

  # For now I don't have tests
  # unit-tests:
  #   runs-on: ubuntu-latest
  #   name: Unit tests
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Set execute permissions for mvnw
  #       run: chmod +x poindexter-network/mvnw

  #     - name: Setup JDK
  #       uses: actions/setup-java@v4
  #       with:
  #         java-version: "17"
  #         distribution: "corretto"

  #     - name: Running Unit Tests
  #       run: |
  #         cd poindexter-network
  #         ./mvnw clean test

  build:
    runs-on: ubuntu-latest
    name: Build backend
    needs: [compile]
    services:
      db:
        container_name: poindexter-db
        image: postgres
        environment:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          PGDATA: /var/lib/postgresql/data
          POSTGRES_DB: poindexter-network
        volumes:
          - postgres:/data/postgres
        ports:
          - 6734:5432
        networks:
          - poindexter-net
        restart: unless-stopped
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set execute permissions for mvnw
        run: chmod +x poindexter-network/mvnw

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "corretto"

      - name: Set environment variables
        run: |
          echo "EMAIL_HOST_NAME=${{ secrets.EMAIL_HOST_NAME }}" >> $GITHUB_ENV
          echo "EMAIL_USER_NAME=${{ secrets.EMAIL_USER_NAME }}" >> $GITHUB_ENV
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          

      - name: Build project
        run: |
          cd poindexter-network
          ./mvnw clean package

  build-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set execute permissions for mvnw
        run: chmod +x poindexter-network/mvnw

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "corretto"
      
      - name: Set environment variables
        run: |
          echo "EMAIL_HOST_NAME=${{ secrets.EMAIL_HOST_NAME }}" >> $GITHUB_ENV
          echo "EMAIL_USER_NAME=${{ secrets.EMAIL_USER_NAME }}" >> $GITHUB_ENV
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV

      - name: Build project
        run: |
          cd poindexter-network
          ./mvnw clean package

      - name: Extract project version
        id: extract_version
        run: |
          cd poindexter-network
          echo "VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: poindexter-network
          file: docker/server/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pn-api:${{ env.VERSION }},${{ secrets.DOCKERHUB_USERNAME }}/pn-api:latest
          build-args: |
            PROFILE=dev
            APP_VERSION=${{ env.VERSION }}

# TO-DO: set-up VPS first
# deploy:
#   name: Deploy Server
#   runs-on: self-hosted
#   needs: [build-image]
#   steps:
#     - name: Create deployment folder
#       run: ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "mkdir -p ci-cd"

#     - name: Copy docker-compose file
#       run: scp -oStrictHostKeyChecking=no docker-compose.yml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:ci-cd/docker-compose.yml

#     - name: Set ENV variable and deploy
#       run: |
#         ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} <<EOF
#         export EMAIL_HOST_NAME=${{ secrets.EMAIL_HOST_NAME }}
#         export EMAIL_USER_NAME=${{ secrets.EMAIL_USER_NAME }}
#         export EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
#         cd ci-cd
#         docker compose -f docker-compose.yml pull -q
#         docker compose -f docker-compose.yml up -d
#         EOF

#  health-check:
#    name: API Health Check
#    runs-on: self-hosted
#    needs: [deploy]
#    steps:
#      - name: Check the docker container health status
#        run: |
#          if ! docker ps -a | grep pn-api; then
#            echo "Container is not running"
#            exit 1
#          fi
